title: Reading Podcast
email: qwh005007@gmail.com
description: >-
  Reading latest news from different sites.
baseurl: ""
url: ""
# twitter_username: jekyllrb
github_username:  qiwihui
permalink: /:categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
